[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = ['csv']

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
    nnoremap <leader>n :NERDTreeFocus<CR>
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown']
hook_add = '''
    nmap <Leader>md <Plug>MarkdownPreview
'''

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
hook_add = '''
    call skkeleton#config({'globalJisyo': '~/.skk/SKK-JISYO.L'})
    imap <C-j> <Plug>(skkeleton-toggle)
    cmap <C-j> <Plug>(skkeleton-toggle)
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
on_cmd = ['Files',
          'GFiles',
          'GFiles?',
          'Buffer',
          'History',
          'Rg',
]
hook_add = '''
    let $FZF_DEFAULT_OPTS="--layout=reverse"
    "let $FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git/**'"
    let g:fzf_layout = {'up':'~90%', 'window': { 'width': 0.8, 'height': 0.8, 'yoffset':0.5, 'xoffset':0.5, 'border': 'sharp' }}
    nnoremap <silent> <leader>f :Files<CR>
    nnoremap <silent> <leader>g :GFiles<CR>
    nnoremap <silent> <leader>G :GFiles?<CR>
    nnoremap <silent> <leader>b :Buffer<CR>
    nnoremap <silent> <leader>h :History<CR>
    nnoremap <silent> <leader>r :Rg<CR>
'''

[[plugins]]
repo = 'tpope/vim-surround'
